version: "3.8"

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/symfony_docker
    depends_on:
      - database
  frontend:
    container_name: frontend
    restart: unless-stopped
    tty: true
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - ./backend:/var/www/symfony_docker
    depends_on:
      - backend
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/app
      - ./backend:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - database
