version: "3.8"

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/symfony_docker
    depends_on:
      - database
  app:
    container_name: app
    restart: unless-stopped
    tty: true
    build:
      context: ./app
    ports:
      - "4200:4200"
    volumes:
      - ./app:/app
      - ./api:/var/www/symfony_docker
    depends_on:
      - api
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app/dist:/var/www/dist
      - ./api:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - api
      - database
